version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend-service
    ports:
      - "4001:4001"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend-service
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
