name: Deploy to AWS ECS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-south-1
  ECR_FRONTEND_REPO: frontend
  ECR_BACKEND_REPO: backend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init -upgrade

    #   - name: Import IAM Role (ecsTaskExecutionRole)
    #     working-directory: ./terraform
    #     run: |
    #       terraform import aws_iam_role.ecs_task_execution ecsTaskExecutionRole || echo "Role already imported"

      - name: Terraform Plan
        working-directory: ./terraform
        run: |
          terraform plan  \
            -var="frontend_image_tag=${{ github.sha }}" \
            -var="backend_image_tag=${{ github.sha }}" \
            -var="mongo_uri=${{ secrets.MONGO_URI }}" \
            -out=tfplan

      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve tfplan
